// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hqwhaciqphakhjhwcsie.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imhxd2hhY2lxcGhha2hqaHdjc2llIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE0MTIzNDcsImV4cCI6MjA2Njk4ODM0N30.BbeyH-WjEW1nGlL8ONJPahtVt-FWwblE_ZqU79F57XQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});